print("Hello there, my name is Walter and I have here today my Mad-Lib")
a1 = input("A verb (without ing)?")
a2 = input("A city name?")
a3 = input("A name of a person or pet?")
a4 = input("a noun for an object?")
a5 = input("The object he bought?")
a6 = input("A name for the friend?")
a7 = input("Name of person that friend needs to pay off the money?")
a8 = input("An animal?")
a9 = input("A name of a toy that can move remotly or on its own?")
a10 = input("A name?")
a11 = input("The animal you choose? ")
a12 = input("What did the animal do? (with a verb that ends with ing) ")
a13 = input("A clothing item?")
a14 = input("The noun of who he was going home too?")
a15 = input("What he did going up the steps?")
print(" There was a man who was on his way home. He had to " + a1 +  " through the city of " + a2 + " to get back home to see " + a3 +" He had passed a couple of normal people and the occasional loony, but there was one man above them all. He stopped them and told him, 'I have about a dozen of " + a4 + " if you want them.' The man felt like he needed to buy the dozen so he did just so. The man walked away with his dozen of "+ a5 +" but soon he ran into his friend " + a6 +" who requested half. 'I need half of them to sell so I can pay off " + a7 +" that kidnapped my goldfish.' The man didn't oblige and gave his friend half the dozen.")
print("Later on, when the man got on the train, he saw a " + a8 +" chasing a toy " + a9 +" The man thought that that was strange, but soon from off the top of the train roof, dropped a " + a10 +"  that started to do karate moves. The " + a11 +" ended up " + a12 +" him and he fell to the floor. Soon the train stopped and there was a bunch of chickens wearing " + a13 +" waiting outside the train. Once the man got off, they got on. When the man got home, he greeted he " + a14 +" gave them a hug, then " + a15 +" his way up the steps to his room.")