print("Hello, my name is Walter the Genie")
a = input("Hello Genie, I come here today to ask for three wishes.")
wish1 = input("a lightskin with curly hair,")
wish2 = input("a supreme ruling over the world,")
wish3 = input("a mansion,")
print()"I, Walter the Genie, wish grant "+ wish1," "+ wish2," AND "+ wish3")